import { gql } from '@apollo/client';

export const SET_SAMPLE_DATASETS = gql`
  mutation StartSampleDataset($data: SampleDatasetInput!) {
    startSampleDataset(data: $data)
  }
`;

export const LIST_DATA_SOURCE_TABLES = gql`
  query ListDataSourceTables {
    listDataSourceTables {
      name
      columns {
        name
        type
      }
    }
  }
`;

export const AUTO_GENERATED_RELATIONS = gql`
  query AutoGeneratedRelations {
    autoGenerateRelation {
      id
      displayName
      referenceName
      relations {
        fromModelId
        fromModelReferenceName
        fromColumnId
        fromColumnReferenceName
        toModelId
        toModelReferenceName
        toColumnId
        toColumnReferenceName
        type
        name
      }
    }
  }
`;

export const SAVE_DATA_SOURCE = gql`
  mutation SaveDataSource($data: DataSourceInput!) {
    saveDataSource(data: $data) {
      type
      properties
    }
  }
`;

export const UPDATE_DATA_SOURCE = gql`
  mutation UpdateDataSource($data: UpdateDataSourceInput!) {
    updateDataSource(data: $data) {
      type
      properties
    }
  }
`;

export const SAVE_TABLES = gql`
  mutation SaveTables($data: SaveTablesInput!) {
    saveTables(data: $data)
  }
`;

export const SAVE_RELATIONS = gql`
  mutation SaveRelations($data: SaveRelationInput!) {
    saveRelations(data: $data)
  }
`;

export const GET_SCHEMA_CHANGE = gql`
  query SchemaChange {
    schemaChange {
      deletedTables {
        sourceTableName
        displayName
        columns {
          sourceColumnName
          displayName
          type
        }
        relationships {
          displayName
          referenceName
        }
        calculatedFields {
          displayName
          referenceName
          type
        }
      }
      deletedColumns {
        sourceTableName
        displayName
        columns {
          sourceColumnName
          displayName
          type
        }
        relationships {
          displayName
          referenceName
        }
        calculatedFields {
          displayName
          referenceName
          type
        }
      }
      modifiedColumns {
        sourceTableName
        displayName
        columns {
          sourceColumnName
          displayName
          type
        }
        relationships {
          displayName
          referenceName
        }
        calculatedFields {
          displayName
          referenceName
          type
        }
      }
      lastSchemaChangeTime
    }
  }
`;

export const TRIGGER_DATA_SOURCE_DETECTION = gql`
  mutation TriggerDataSourceDetection {
    triggerDataSourceDetection
  }
`;

export const RESOLVE_SCHEMA_CHANGE = gql`
  mutation ResolveSchemaChange($where: ResolveSchemaChangeWhereInput!) {
    resolveSchemaChange(where: $where)
  }
`;

// Dataset discovery queries for BigQuery
export const DISCOVER_DATASETS = gql`
  query DiscoverDatasets($projectId: Int!) {
    discoverDatasets(projectId: $projectId) {
      success
      datasets {
        id
        friendlyName
        description
        location
        creationTime
        lastModifiedTime
      }
      error {
        code
        message
        requiresManualInput
      }
    }
  }
`;

export const LIST_TABLES_FROM_DATASETS = gql`
  query ListTablesFromDatasets($projectId: Int!, $datasetIds: [String!]!) {
    listTablesFromDatasets(projectId: $projectId, datasetIds: $datasetIds) {
      name
      columns {
        name
        type
        properties
      }
      properties
    }
  }
`;

export const VALIDATE_DATASET_ACCESS = gql`
  query ValidateDatasetAccess($projectId: Int!, $datasetIds: [String!]!) {
    validateDatasetAccess(projectId: $projectId, datasetIds: $datasetIds) {
      accessible
      inaccessible
    }
  }
`;
